spring:
  datasource:
    url: jdbc:mysql://localhost:3306/d1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 50 # 初始化连接池大小
      minIdle: 50 # 最小连接数
      maxActive: 200 # 最大连接数
      max-wait: 60000 # 单位ms 1分钟内无法获取到连接抛出异常。默认值-1 无限等待。
      time-between-eviction-runs-millis: 60000 # 单位ms 连接池每次检测空闲连接的间隔时间，默认1分钟。
      min-evictable-idle-time-millis: 300000 # 单位ms 空闲5分钟的连接将被回收
      validation-query: SELECT 1 # 定期执行此查询来检测连接的可用性，默认"SELECT 1"。
      test-while-idle: true # 连接空闲时检测连接的有效性，定期检测空闲连接，如果连接失效，就标记为不可用并移除。默认 true。
      test-on-borrow: false # 每次从连接池拿连接时检测连接的有效性。默认 false。
      test-on-return: false # 每次归还连接到连接池时检测连接的有效性。默认 false。
      pool-prepared-statements: true # 开启预处理语句池。在执行相同SQL语句多次时，提高性能。默认 true。
      max-pool-prepared-statement-per-connection-size: 20 # 每个连接上允许的最大预处理语句数。默认 20。
      keep-alive: true
      query-timeout: 6000
      default-read-only: false
      filters: config,stat,wall,slf4j
        #web-stat-filter: #配置过滤器，过滤掉静态文件
        #enabled: true
        #url-pattern: /*
        #exclusions: /druid/*,*.js,*.css,*.gif,*.jpg,*.bmp,*.png,*.ico
        #stat-view-servlet: #配置可视化控制台页面
        #enabled: true
        #url-pattern: /druid/*
        #allow: #IP白名单 没有配置或者为空 则允许所有访问
        #deny:  #IP黑名单 若白名单也存在 则优先使用
        #reset-enable: true #禁用重置按钮
      #login-username: admin
      #login-password: admin

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

