server:
  port: 9999
spring:
  application:
    name: ins-wisps-rpc
  cloud:
    nacos:
      server-addr: localhost:8848
    openfeign:
      client:
        config:
          default:
            connectTimeout: 60000
            readTimeout: 100
feign:
  sentinel:
    enabled: true