server:
  port: 8888
spring:
  application:
    name: ins-wisps-user
  cloud:
    nacos:
      server-addr: localhost:8848
#      discovery:
#        server-addr: localhost:8848
#        namespace: d41a46f7-3b64-44c0-ab9f-b5766ca386d3
#        group: wisps
#        username: nacos
#        password: nacos
#
#dubbo:
#  application:
#    name: ins-wisps-user
#    qos-enable: false
#  registry:
#    address: nacos://localhost:8848?namespace=d41a46f7-3b64-44c0-ab9f-b5766ca386d3&group=wisps&username=nacos&password=nacos
#  protocols:
#    dubbo:
#      id: dubbo
#      name: dubbo
#      port: -1          # 随机端口
#    rest:
#      id: rest
#      name: rest
#      port: 8888        # 固定 REST 端口
#  provider:
#    protocol: dubbo,rest   # 双协议同时暴露
#  scan:
#    base-packages: com.wisps.**.service